name: Auto Create PR from Production to Main

on:
  push:
    branches:
      - production

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ensure all branches are fetched
      - name: Fetch all branches
        run: git fetch --all


      # Step: Force create or update the temporary branch from production
      - name: Force create or update temporary branch from production
        if: env.has_changes == 'true'
        run: |
          git checkout production  # Checkout the production branch
          git pull origin production  # Ensure the latest changes are pulled

          # Create or reset the sync/production-to-main branch from production
          git checkout -B sync/production-to-main production  # Always create or reset the branch from production
          git push --force origin sync/production-to-main  # Force push to remote

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Auto created pull request
          branch: main
          base: sync/production-to-main
          title: 'Sync `production` with `main`'
          body: |
            This PR is automatically created to keep `main` branch in sync with changes merged into `production`.
