name: Auto Create PR from Production to Main

on:
  push:
    branches:
      - production

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ensure all branches are fetched
      - name: Fetch all branches
        run: git fetch --all

      # Step: Force create or update the temporary branch from production
      - name: Force create or update temporary branch from production
        if: env.has_changes == 'true'
        run: |
          # Checkout production to ensure we start from the right state
          git checkout production
          git pull origin production

          # Create or reset the sync branch based on production
          git branch -D sync/production-to-main || true  # Delete if it exists
          git checkout -b sync/production-to-main  # Create branch
          git push --force origin sync/production-to-main  # Push to remote

      # Step: Create the Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Auto created pull request
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
          branch: sync/production-to-main
=======
          branch: sync/production
>>>>>>> 1cddb6e (initial)
=======
          branch: sync/production-to-main
>>>>>>> fe6e018 (initial)
          base: main
=======
          branch: production
<<<<<<< HEAD
>>>>>>> 4022225 (initial)
=======
          base: main
>>>>>>> 1183195 (initial)
          title: 'Sync `production` with `main`'
          body: |
            This PR is automatically created to keep `main` branch in sync with changes merged into `production`.