name: Auto Create PR from Production to Main

on:
  push:
    branches:
      - prod

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ensure all branches are fetched
      - name: Fetch all branches
        run: git fetch --all

      # Reset or create the sync branch
      - name: Reset or create sync branch
        run: |
          # Check if the remote branch already exists
          if git ls-remote --exit-code --heads origin sync/prod-to-main; then
            # If it exists, delete the remote branch
            git push origin --delete sync/prod-to-main
          fi

          # Checkout production and create/reset the sync branch
          git checkout prod
          git pull origin prod
          git checkout -b sync/prod-to-main
          git push --force origin sync/prod-to-main


      # Step: Create the Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Auto created pull request
          branch: sync/prod-to-main
          base: main
          title: 'Sync `production` with `main`'
          reviewers: eaponiente
          body: |
            This PR is automatically created to keep `main` branch in sync with changes merged into `production`.
