name: Auto Create PR from Hotfix to Main

on:
  push:
    branches:
      - hotfix
      - production

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create main pull request
        id: main
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "Sync ${{ github.ref_name }} into main"
          pr_allow_empty: true
          pr_body: "**Automated pull request**"
          pr_reviewer: eaponiente
          pr_label: sync
          github_token: ${{ secrets.GITHUB_TOKEN }}
