name: Auto Create PR from Production to Main

on:
  push:
    branches:
      - production

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

<<<<<<< HEAD
<<<<<<< HEAD
      # Ensure all branches are fetched
      - name: Fetch all branches
        run: git fetch --all

      # Step: Force create or update the temporary branch from production
      - name: Force create or update temporary branch from production
        run: |
          # Checkout production to ensure we start from the right state
          git checkout production
          git pull origin production

          # Create or reset the sync branch based on production
          git branch -D sync/production-to-main || true  # Delete if it exists
          git checkout -b sync/production-to-main  # Create branch
          git push --force origin sync/production-to-main  # Push to remote

      # Step: Create the Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Auto created pull request
          branch: sync/production-to-main
          base: main
=======
=======
      # Make sure that the temporary branch exists by checking all branch
      - name: Fetch all branches
        run: git fetch --all

      # Step 3: Check for differences between production and main
      - name: Check for differences
        id: check_diff
        run: |
          git diff --quiet origin/main..HEAD || echo "has_changes=true" >> $GITHUB_ENV
  
      - name: Create or update temporary branch from production
        if: env.has_changes == 'true'
        run: |
          git checkout production  # Checkout the production branch
          git pull origin production  # Ensure the latest changes are pulled

          # Check if the sync/production-to-main branch exists
          if git show-ref --verify --quiet refs/heads/sync/production-to-main; then
            # If the branch exists, checkout and reset it to production
            git checkout sync/production-to-main
            git reset --hard production  # Reset it to match production exactly
            git push --force origin sync/production-to-main  # Force push to the remote
          else
            # If the branch doesn't exist, create it from production
            git checkout -b sync/production-to-main
            git push origin sync/production-to-main  # Push the new branch to remote
          fi


>>>>>>> fe6e018 (initial)
      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Auto created pull request
<<<<<<< HEAD
<<<<<<< HEAD
          branch: production
<<<<<<< HEAD
>>>>>>> 4022225 (initial)
=======
=======
          branch: sync/production
>>>>>>> 1cddb6e (initial)
=======
          branch: sync/production-to-main
>>>>>>> fe6e018 (initial)
          base: main
>>>>>>> 1183195 (initial)
          title: 'Sync `production` with `main`'
          body: |
            This PR is automatically created to keep `main` branch in sync with changes merged into `production`.