name: Auto Create PR from Production to Main

on:
  push:
    branches:
      - production

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ensure all branches are fetched
      - name: Fetch all branches
        run: git fetch --all

      # Step: Create the Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Auto created pull request
          branch: pr
          base: main
          title: 'Sync `production` with `main`'
          body: |
            This PR is automatically created to keep `main` branch in sync with changes merged into `production`.