name: TEST CREATE PR

on:
  push:
    branches:
      - prod

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step: Create the Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Auto created pull request
          branch: main
          base: sync/production-to-main
          title: 'Sync `production` with `main`'
          body: |
            This PR is automatically created to keep `main` branch in sync with changes merged into `production`.
